### ISSUE TITLE
Request for ICDAR 2019 dataset 

### ISSUE THREAD

**Issue by Hrishkesh** [antoinedelplace/Chargrid#1]
Hello,
Can i request you for the ICDAR 2019 data set samples with respective Json file.
As I am currently working on a small project and i need for a reference.
It would be helpful for me in my small project.

**Comment by antoinedelplace** [comment]
As written in the README, you can find the dataset here : Z. Huang et al. ICDAR 2019 Robust Reading Challenge on Scanned Receipts OCR and Information Extraction, ICDAR, 2019, 2019. [link](https://rrc.cvc.uab.es/?ch=13)
