### ISSUE TITLE
chargrid_pd[chargrid_pd['ord']>=33

### ISSUE THREAD

**Issue by mattlistrom** [antoinedelplace/Chargrid#2]
Please explain how this part of preprocessing.py relates to the model:

    chargrid_pd = chargrid_pd[chargrid_pd['ord']>=33]
    chargrid_pd = chargrid_pd[chargrid_pd['ord']<=126]
    chargrid_pd['ord'] -= 32

**Comment by ziodos** [comment]
@mattlistrom I think he is just conserving the characters which ASCII code are between 33 and 126 and then ordering them starting from 1 (33-32)

**Comment by mattlistrom** [comment]
Thanks much for the response @zanina14 . One other question, would you happen to how the probability of the classes were calculated in network.py? 
[0.89096397, 0.01125766, 0.0504345, 0.03237164, 0.01497223]) #other, total, address, company, date

**Comment by ziodos** [comment]
@mattlistrom I think after scanning all images , the model extract the words that can belongs to a specific class so for example if we had  10,1,2,3,4(number of words that belongs to other,total,adress,company,date) then probabilities will be calculated as following [10/(10+1+2+3+4) 1/(10+1+2+3+4 ..... and so on ]
