### ISSUE TITLE
Invalid keyword argument(s) in `compile`: {'sample_weight'} in network.py

### ISSUE THREAD

**Issue by mattlistrom** [antoinedelplace/Chargrid#3]
Is it as simple as moving the sample_weights to .fit()?

**Comment by Hrishkesh** [comment]
Try to use tensorflow verson: 2.0.0 to run the code if your using higher version of it.
as you can see in the tensorflow documentation   https://www.tensorflow.org/api_docs/python/tf/keras/Model  of compile there is no such attribute called sample_weight it's sample_weight_mode so may be earlier version can run through this 
it worked for me!! @mattlistrom
